### PR TITLE
Include passlib as a dependency

### PR DESCRIPTION
**Pull request by m-czernek**
We added passlib to Salt bundle, but not here; WDYT?

### CODE REVIEW

**Review by vzhestkov — CHANGES_REQUESTED** [review]
Are you sure it's a build requirement? I suppose it should be the requirement for the package installation, so `Requires:       python3-passlib`, and I'm not sure if it should be a strict requirement, maybe better to use `Recommends`. With `Requires` most probably we need to adjust the bootstrap repo definitions to include passlib to the bootstrap repo.

**Comment by m-czernek** [comment]
Changed - I used buildrequires because that's what we use in Bundle, but you're right, it's not a build dep for non-bundle Salt. WDYT now? Also, please double check the location of the recommends - I placed it where I believe it'll apply to all systems (and that should be correct?)

**Review by vzhestkov — APPROVED** [review]
Not fully sure about EL8 clones, some of them has no such package at all, maybe better to move up inside such section:
```
%if 0%{?suse_version}
...
%endif
```
but with `Recommends` it should be fine anyway

**Comment by vzhestkov** [comment]
For the bundle it's in the BuildRequires as it should be available while building the package to include to the resulting, but with the classic salt packages we are not including anything during the build time, so this is the requirement for the package when it's installed on the system.

**Pull request merged**
